module = "Cluster"
interface_names = [
    "Cluster_Node_Remove"
]


[Cluster_Node_Remove]
interface_desc = "从集群移除节点，不能有卷使用该节点"
interface_path = "/cluster/node/remove"
requests_data_time = 3
requests_data_1 = { req_host="172.18.123.73", node_addr="172.169.100.71" }
requests_data_2 = { req_host="172.18.123.73", node_addr="172.169.100.72" }
requests_data_3 = { req_host="172.18.123.73", node_addr="172.169.100.73" }