module = "Cluster"
interface_names = [
#    "Cluster_Version_Info",
#    "Cluster_Op_Version_Info",
#    "Cluster_Node_List",
#    "Cluster_Node_Init",
    "Cluster_Node_Append",
#    "Cluster_Config_Sync",
]


[Cluster_Version_Info]
interface_desc = "获取glusterfs版本信息"
interface_path = "/cluster/version/info"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


[Cluster_Op_Version_Info]
interface_desc = "获取glusterd协议版本"
interface_path = "/cluster/op_version/info"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


[Cluster_Node_List]
interface_desc = "获取集群节点列表"
interface_path = "/cluster/node/list"
requests_data_time = 3
requests_data_1 = { req_host="172.18.123.71" }
requests_data_2 = { req_host="172.18.123.72" }
requests_data_3 = { req_host="172.18.123.73" }


[Cluster_Node_Init]
interface_desc = "初始化节点服务"
interface_path = "/cluster/node/init"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


[Cluster_Node_Append]
interface_desc = "向集群添加节点"
interface_path = "/cluster/node/append"
requests_data_time = 3
requests_data_1 = { req_host="172.18.123.73", node_addr="172.169.100.71" }
requests_data_2 = { req_host="172.18.123.73", node_addr="172.169.100.72" }
requests_data_3 = { req_host="172.18.123.73", node_addr="172.169.100.73" }



[Cluster_Config_Sync]
interface_desc = "同步节点信息，通常用于节点理想恢复后"
interface_path = "/cluster/node/sync"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }

