module = "Storage"
interface_names = [
    "Block_Device_Status",
    "Block_Device_Disable",
    "Block_Device_Wipe"
]


[Block_Device_Status]
interface_desc = "获取节点所有块设备状态信息列表"
interface_path = "/storage/block_device/status"
requests_data_time = 3
requests_data_1 = { req_host="172.18.123.71" }
requests_data_2 = { req_host="172.18.123.72" }
requests_data_3 = { req_host="172.18.123.73" }


[Block_Device_Disable]
interface_desc = "卸载块设备并取消开机挂载"
interface_path = "/storage/block_device/disable"
requests_data_time = 18
requests_data_1 = { req_host="172.18.123.71", dev_path="/dev/sdb" }
requests_data_2 = { req_host="172.18.123.71", dev_path="/dev/sdc" }
requests_data_3 = { req_host="172.18.123.71", dev_path="/dev/sdd" }
requests_data_4 = { req_host="172.18.123.71", dev_path="/dev/sde" }
requests_data_5 = { req_host="172.18.123.71", dev_path="/dev/sdf" }
requests_data_6 = { req_host="172.18.123.71", dev_path="/dev/sdg" }
requests_data_7 = { req_host="172.18.123.72", dev_path="/dev/sdb" }
requests_data_8 = { req_host="172.18.123.72", dev_path="/dev/sdc" }
requests_data_9 = { req_host="172.18.123.72", dev_path="/dev/sdd" }
requests_data_10 = { req_host="172.18.123.72", dev_path="/dev/sde" }
requests_data_11 = { req_host="172.18.123.72", dev_path="/dev/sdf" }
requests_data_12 = { req_host="172.18.123.72", dev_path="/dev/sdg" }
requests_data_13 = { req_host="172.18.123.73", dev_path="/dev/sdb" }
requests_data_14 = { req_host="172.18.123.73", dev_path="/dev/sdc" }
requests_data_15 = { req_host="172.18.123.73", dev_path="/dev/sdd" }
requests_data_16 = { req_host="172.18.123.73", dev_path="/dev/sde" }
requests_data_17 = { req_host="172.18.123.73", dev_path="/dev/sdf" }
requests_data_18 = { req_host="172.18.123.73", dev_path="/dev/sdg" }


[Block_Device_Wipe]
interface_desc = "清除指定块设备的文件系统"
interface_path = "/storage/block_device/wipe"
requests_data_time = 18
requests_data_1 = { req_host="172.18.123.71", dev_path="/dev/sdb" }
requests_data_2 = { req_host="172.18.123.71", dev_path="/dev/sdc" }
requests_data_3 = { req_host="172.18.123.71", dev_path="/dev/sdd" }
requests_data_4 = { req_host="172.18.123.71", dev_path="/dev/sde" }
requests_data_5 = { req_host="172.18.123.71", dev_path="/dev/sdf" }
requests_data_6 = { req_host="172.18.123.71", dev_path="/dev/sdg" }
requests_data_7 = { req_host="172.18.123.72", dev_path="/dev/sdb" }
requests_data_8 = { req_host="172.18.123.72", dev_path="/dev/sdc" }
requests_data_9 = { req_host="172.18.123.72", dev_path="/dev/sdd" }
requests_data_10 = { req_host="172.18.123.72", dev_path="/dev/sde" }
requests_data_11 = { req_host="172.18.123.72", dev_path="/dev/sdf" }
requests_data_12 = { req_host="172.18.123.72", dev_path="/dev/sdg" }
requests_data_13 = { req_host="172.18.123.73", dev_path="/dev/sdb" }
requests_data_14 = { req_host="172.18.123.73", dev_path="/dev/sdc" }
requests_data_15 = { req_host="172.18.123.73", dev_path="/dev/sdd" }
requests_data_16 = { req_host="172.18.123.73", dev_path="/dev/sde" }
requests_data_17 = { req_host="172.18.123.73", dev_path="/dev/sdf" }
requests_data_18 = { req_host="172.18.123.73", dev_path="/dev/sdg" }

