# _*_ coding: utf-8 _*_

module = "Volume"
interface_names = [
    "Cluster_Volume_Create",
    "Cluster_Volume_Start"
]


[Cluster_Volume_Create]
interface_desc = "创建卷"
interface_path = "/cluster/volume/create"
requests_data_time = 1
[Cluster_Volume_Create.requests_data_1]
req_host="172.18.123.73"
vol_name="vol-01"
remote_mnts=[
    "node-01.xdfs.com:/data/12345678-1234-1234-1234-12345678901b",
    "node-02.xdfs.com:/data/12345678-1234-1234-1234-12345678901b",
    "node-03.xdfs.com:/data/12345678-1234-1234-1234-12345678901b",
    "node-01.xdfs.com:/data/12345678-1234-1234-1234-12345678901c",
    "node-02.xdfs.com:/data/12345678-1234-1234-1234-12345678901c",
    "node-03.xdfs.com:/data/12345678-1234-1234-1234-12345678901c"
    ]
vol_type="Disperse"
vol_pattern="2:1"
rdma=false


[Cluster_Volume_Start]
interface_desc = "开启卷"
interface_path = "/cluster/volume/start"
requests_data_time = 1
[Cluster_Volume_Start.requests_data_1]
req_host="172.18.123.73"
vol_name="vol-01"