# _*_ coding: utf-8 _*_

module = "Volume"
interface_names = [
    "Cluster_Volume_Create",
    "Cluster_Volume_Start",
    "Cluster_Volume_Info",
    "Cluster_Volume_Status"
]


[Cluster_Volume_Info]
interface_desc = "获取所有卷信息列表"
interface_path = "/cluster/volume/info"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


[Cluster_Volume_Status]
interface_desc = "获取所有卷状态列表"
interface_path = "/cluster/volume/status"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


[Cluster_Volume_Create]
interface_desc = "创建卷"
interface_path = "/cluster/volume/create"
requests_data_time = 1
[Cluster_Volume_Create.requests_data_1]
req_host="172.18.123.73"
vol_name="vol-03"
remote_mnts=[
    "node-01.xdfs.com:/data/12345678-1234-1234-1234-12345678903b",
    "node-02.xdfs.com:/data/12345678-1234-1234-1234-12345678903b",
    "node-03.xdfs.com:/data/12345678-1234-1234-1234-12345678903b",
    "node-01.xdfs.com:/data/12345678-1234-1234-1234-12345678903c",
    "node-02.xdfs.com:/data/12345678-1234-1234-1234-12345678903c",
    "node-03.xdfs.com:/data/12345678-1234-1234-1234-12345678903c"
    ]
vol_type="Repalica"
vol_pattern="3"
rdma=false


[Cluster_Volume_Start]
interface_desc = "开启卷"
interface_path = "/cluster/volume/start"
requests_data_time = 1
[Cluster_Volume_Start.requests_data_1]
req_host="172.18.123.73"
vol_name="vol-03"

