# _*_ coding: utf-8 _*_

module = "Volume"
interface_names = [
    "Cluster_Volume_Create",
    "Cluster_Volume_Start",
    "Cluster_Volume_Info",
    "Cluster_Volume_Status",
#    "Cluster_Volume_Extend",
#    "Cluster_Volume_Force_Shirk",
#    "Volume_Brick_Force_Replace"
]


[Cluster_Volume_Info]
interface_desc = "获取所有卷信息列表"
interface_path = "/cluster/volume/info"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


[Cluster_Volume_Status]
interface_desc = "获取所有卷状态列表"
interface_path = "/cluster/volume/status"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


[Cluster_Volume_Create]
interface_desc = "创建卷"
interface_path = "/cluster/volume/create"
requests_data_time = 1
[Cluster_Volume_Create.requests_data_1]
req_host="172.18.123.73"
vol_name="vol-01"
remote_mnts=[
    "node-01.xdfs.com:/data/12345678-1234-1234-1234-12345678901b",
    "node-02.xdfs.com:/data/12345678-1234-1234-1234-12345678901b",
    "node-03.xdfs.com:/data/12345678-1234-1234-1234-12345678901b",
    "node-01.xdfs.com:/data/12345678-1234-1234-1234-12345678901c",
    "node-02.xdfs.com:/data/12345678-1234-1234-1234-12345678901c",
    "node-03.xdfs.com:/data/12345678-1234-1234-1234-12345678901c"
    ]
vol_type="Repalica"
vol_pattern="3"
rdma=false


[Cluster_Volume_Start]
interface_desc = "开启卷"
interface_path = "/cluster/volume/start"
requests_data_time = 1
[Cluster_Volume_Start.requests_data_1]
req_host="172.18.123.73"
vol_name="vol-01"


[Cluster_Volume_Extend]
interface_desc = "卷扩容，扩容后需要手动启动均衡"
interface_path = "/cluster/volume/extend"
requests_data_time = 1
[Cluster_Volume_Extend.requests_data_1]
req_host="172.18.123.73"
vol_name="vol-01"
remote_mnts=[
    "node-01.xdfs.com:/data/12345678-1234-1234-1234-12345678902b",
    "node-02.xdfs.com:/data/12345678-1234-1234-1234-12345678902b",
    "node-03.xdfs.com:/data/12345678-1234-1234-1234-12345678902b"
    ]


[Cluster_Volume_Force_Shirk]
interface_desc = "卷强制缩容，会引起数据丢失"
interface_path = "/cluster/volume/force_shirk"
requests_data_time = 1
[Cluster_Volume_Force_Shirk.requests_data_1]
req_host="172.18.123.73"
vol_name="vol-01"
remote_mnts=[
    "node-01.xdfs.com:/data/12345678-1234-1234-1234-12345678902b",
    "node-02.xdfs.com:/data/12345678-1234-1234-1234-12345678902b",
    "node-03.xdfs.com:/data/12345678-1234-1234-1234-12345678902b"
    ]


[Volume_Brick_Force_Replace]
interface_desc = "强制替换Brick，替换后需要进行数据修复"
interface_path = "/cluster/volume/brick/force_replace"
requests_data_time = 1
[Volume_Brick_Force_Replace.requests_data_1]
req_host="172.18.123.73"
vol_name="vol-01"
src_remote_mnt="node-01.xdfs.com:/data/12345678-1234-1234-1234-12345678901b"
dst_remote_mnt="node-01.xdfs.com:/data/12345678-1234-1234-1234-12345678902c"

