module = "NFS"
interface_names = [
    "Gluster_Nfs_Service_Status",
    "Gluster_NFS_Service_Init",
    "Gluster_NFS_Service_Enable",
    "Gluster_NFS_Service_Disable",
    "Gluster_NFS_Share_List",
    "Gluster_NFS_Share_Update",
    "Gluster_NFS_Share_Delete",
    "Kernel_NFS_Service_Status",
    "Kernel_NFS_Service_Init",
    "Kernel_NFS_Service_Enable",
    "Kernel_NFS_Service_Disable",
    "Kernel_NFS_Share_List",
    "Kernel_NFS_Share_Update",
    "Kernel_NFS_Share_Delete",
    "NFS_Client_Status"
]


[Gluster_Nfs_Service_Status]
interface_desc = "获取集群所有节点Gluster-NFS服务状态"
interface_path = "/nfs/gluster/service/status"
requests_data_time = 1
requests_data_1 = {}


[Gluster_NFS_Service_Init]
interface_desc = "初始化Gluster-NFS配置"
interface_path = "/nfs/gluster/service/init"
requests_data_time = 1
requests_data_1 = {}


[Gluster_NFS_Service_Enable]
interface_desc = "开启集群所有节点Gluster-NFS服务"
interface_path = "/nfs/gluster/service/enable"
requests_data_time = 1
requests_data_1 = {}


[Gluster_NFS_Service_Disable]
interface_desc = "关闭集群所有节点Gluster-NFS服务"
interface_path = "/nfs/gluster/service/disable"
requests_data_time = 1
requests_data_1 = {}


[Gluster_NFS_Share_List]
interface_desc = "获取Gluster-NFS共享列表"
interface_path = "/nfs/gluster/share/list"
requests_data_time = 1
requests_data_1 = {}


[Gluster_NFS_Share_Update]
interface_desc = "创建/更新Gluster-NFS共享；同步到所有集群节点。"
interface_path = "/nfs/gluster/share/update"
requests_data_time = 1
requests_data_1 = { vol_name="vol1", share_dir="/tmp/subdir-01", client="*", options=["rw", "sync"] }


[Gluster_NFS_Share_Delete]
interface_desc = "删除Gluster-NFS共享 同步到所有集群节点"
interface_path = "/nfs/gluster/share/delete"
requests_data_time = 1
requests_data_1 = { vol_name="vol1", share_dir="/tmp/subdir-01", client="*" }


[Kernel_NFS_Service_Status]
interface_desc = "获取本节点Kernel-NFS服务状态"
interface_path = "/nfs/kernel/service/status"
requests_data_time = 1
requests_data_1 = {}


[Kernel_NFS_Service_Init]
interface_desc = "初始化Kernel-NFS配置"
interface_path = "/nfs/kernel/service/init"
requests_data_time = 1
requests_data_1 = {}


[Kernel_NFS_Service_Enable]
interface_desc = "开启本节点Kernel-NFS服务"
interface_path = "/nfs/kernel/service/enable"
requests_data_time = 1
requests_data_1 = {}


[Kernel_NFS_Service_Disable]
interface_desc = "关闭本节点Kernel-NFS服务"
interface_path = "/nfs/kernel/service/disable"
requests_data_time = 1
requests_data_1 = {}


[Kernel_NFS_Share_List]
interface_desc = "获取Kernel-NFS共享列表"
interface_path = "/nfs/kernel/share/list"
requests_data_time = 1
requests_data_1 = {}


[Kernel_NFS_Share_Update]
interface_desc = "创建/更新Kernel-NFS共享"
interface_path = "/nfs/kernel/share/update"
requests_data_time = 1
requests_data_1 = { vol_name="vol1", share_dir="/tmp/subdir-02", client="*", options=["rw", "sync", "fsid=45fa990f-bc07-57ac-9d27-64fbef11ac3b"] }


[Kernel_NFS_Share_Delete]
interface_desc = "删除Kernel-NFS共享"
interface_path = "/nfs/kernel/share/delete"
requests_data_time = 1
requests_data_1 = { vol_name="vol1", share_dir="/tmp/subdir-02", client= "*" }


[NFS_Client_Status]
interface_desc = "获取NFS客户端连接状态"
interface_path = "/nfs/client/status"
requests_data_time = 1
requests_data_1 = {}
