module = "iSCSI"
interface_names = [
    "Tgt_Service_Status",
    "Tgt_Service_Init",
    "Tgt_Service_Enable",
#    "Tgt_Service_Disable",
    "Tgt_User_List",
    "Tgt_User_Update",
#    "Tgt_User_Delete",
    "Tgt_User_Status",
    "Tgt_Lun_List",
    "Tgt_Lun_Update",
#    "Tgt_Lun_Delete",
    "Tgt_Lun_Status",
    "Tgt_Target_List",
    "Tgt_Target_Update",
#    "Tgt_Target_Delete",
    "Tgt_Target_Status",
    "Tgt_Target_User_Map",
    "Tgt_Target_Lun_Map",
#    "Tgt_Config_Export",
#    "Tgt_Config_Import"
]


[Tgt_Service_Status]
interface_desc = "获取节点TGTD服务状态."
interface_path = "/iscsi/tgt/service/status"
requests_data_time = 1
requests_data_1 = {}


[Tgt_Service_Init]
interface_desc = "初始化TGTD配置."
interface_path = "/iscsi/tgt/service/init"
requests_data_time = 1
requests_data_1 = {}


[Tgt_Service_Enable]
interface_desc = "开启节点TGTD服务."
interface_path = "/iscsi/tgt/service/enable"
requests_data_time = 1
requests_data_1 = {}


[Tgt_Service_Disable]
interface_desc = "关闭节点TGTD服务."
interface_path = "/iscsi/tgt/service/disable"
requests_data_time = 1
requests_data_1 = {}


[Tgt_User_List]
interface_desc = "获取iSCSI用户信息列表."
interface_path = "/iscsi/tgt/user/list"
requests_data_time = 1
requests_data_1 = {}


[Tgt_User_Update]
interface_desc = "添加iSCSI用户/修改用户密码."
interface_path = "/iscsi/tgt/user/update"
requests_data_time = 3
requests_data_1 = { user="user-01", passwd="123456" }
requests_data_2 = { user="user-02", passwd="123456" }
requests_data_3 = { user="user-03", passwd="123456" }


[Tgt_User_Delete]
interface_desc = "删除iSCSI用户."
interface_path = "/iscsi/tgt/user/delete"
requests_data_time = 3
requests_data_1 = { user="user-01" }
requests_data_2 = { user="user-02" }
requests_data_3 = { user="user-03" }


[Tgt_User_Status]
interface_desc = "获取iSCSI用户状态列表."
interface_path = "/iscsi/tgt/user/status"
requests_data_time = 1
requests_data_1 = {}


[Tgt_Lun_List]
interface_desc = "获取iSCSI-Lun列表."
interface_path = "/iscsi/tgt/lun/list"
requests_data_time = 1
requests_data_1 = {}


[Tgt_Lun_Update]
interface_desc = "增加/更新CIFS共享."
interface_path = "/iscsi/tgt/lun/update"
requests_data_time = 1
requests_data_1 = { lun_name="lun-01", lun_size="10 MiB", vol_name="vol1", thin=true, glfs_api=true, ex_args={} }
#requests_data_2 = { lun_name="lun-02", lun_size="10 MiB", vol_name="vol1", thin=true, glfs_api=true, ex_args={} }


[Tgt_Lun_Delete]
interface_desc = "获取节点TGTD服务状态."
interface_path = "/iscsi/tgt/lun/delete"
requests_data_time = 2
requests_data_1 = { lun_name="lun-01", clean_data=true }
requests_data_2 = { lun_name="lun-02", clean_data=true }


[Tgt_Lun_Status]
interface_desc = "删除Lun."
interface_path = "/iscsi/tgt/lun/status"
requests_data_time = 1
requests_data_1 = {}


[Tgt_Target_List]
interface_desc = "获取iSCSI-Target列表."
interface_path = "/iscsi/tgt/target/list"
requests_data_time = 1
requests_data_1 = {}


[Tgt_Target_Update]
interface_desc = "增加/更新iSCSI-Target."
interface_path = "/iscsi/tgt/target/update"
requests_data_time = 1
requests_data_1 = { iqn="iqn.2021-08.cluster-01.target-01", initiator_address=["127.0.0.1"], ex_args={} }


[Tgt_Target_Delete]
interface_desc = "删除iSCSI-Target."
interface_path = "/iscsi/tgt/target/delete"
requests_data_time = 1
requests_data_1 = { iqn="iqn.2021-08.cluster-01.target-01" }


[Tgt_Target_Status]
interface_desc = "删除iSCSI-Target."
interface_path = "/iscsi/tgt/target/status"
requests_data_time = 1
requests_data_1 = {}


[Tgt_Target_User_Map]
interface_desc = "设置iSCSI-Target双向CHAP或CHAP用户."
interface_path = "/iscsi/tgt/target/user_map"
requests_data_time = 1
requests_data_1 = { iqn="iqn.2021-08.cluster-01.target-01", incoming_users=["user-01", "user-02"], outgoing_user="user-03" }


[Tgt_Target_Lun_Map]
interface_desc = "设置iSCSI-Target双向CHAP或CHAP用户."
interface_path = "/iscsi/tgt/target/lun_map"
requests_data_time = 1
requests_data_1 = { iqn="iqn.2021-08.cluster-01.target-01", luns= ["lun-01", "lun-02"] }


[Tgt_Config_Export]
interface_desc = "导出iSCSI配置信息."
interface_path = "/iscsi/tgt/config/export"
requests_data_time = 1
requests_data_1 = {}


[Tgt_Config_Import]
interface_desc = "导入iSCSI配置信息."
interface_path = "/iscsi/tgt/config/import"
requests_data_time = 1
requests_data_1 = {}


# 客户端访问
# yum install -y scsi-target-utils-gluster
# iscsiadm -m discovery -t st -p 172.18.123.73
# iscsiadm --mode node --targetname iqn.2021-08.cluster-01.target-01 --portal 172.18.123.73:3260 --login


# 配置文件
#[root@node3 conf.d]# pwd
#/etc/tgt/conf.d
#[root@node3 conf.d]# ls
#glfs.conf  sample.conf
#[root@node3 conf.d]# cat glfs.conf
#<lun>
#  <vol1@127.0.0.1:/.iSCSI/lun-01>
#    bs-type glfs
#    scsi_sn "vol1:lun-01"
#    scsi_id 766F6C313A6C756E2D3031
#  </vol1@127.0.0.1:/.iSCSI/lun-01>
#  <vol1@127.0.0.1:/.iSCSI/lun-02>
#    bs-type glfs
#    scsi_sn "vol1:lun-02"
#    scsi_id 766F6C313A6C756E2D3032
#  </vol1@127.0.0.1:/.iSCSI/lun-02>
#</lun>
#<target>
#  <iqn.2021-08.cluster-01.target-01>
#    initiator-address "127.0.0.1"
#    initiator-address "172.18.123.0/24"
#    vendor_id TaoCloud
#    product_id XDFS
#    product_rev 0200
#    bs-type rbd
#    <backing-store>
#      <vol1@127.0.0.1:/.iSCSI/lun-01>
#        bs-type glfs
#        scsi_sn "vol1:lun-01"
#        scsi_id 766F6C313A6C756E2D3031
#      </vol1@127.0.0.1:/.iSCSI/lun-01>
#      <vol1@127.0.0.1:/.iSCSI/lun-02>
#        bs-type glfs
#        scsi_sn "vol1:lun-02"
#        scsi_id 766F6C313A6C756E2D3032
#      </vol1@127.0.0.1:/.iSCSI/lun-02>
#    </backing-store>
#  </iqn.2021-08.cluster-01.target-01>
#</target>


# https://fedoraproject.org/wiki/Scsi-target-utils_Quickstart_Guide
# https://staged-gluster-docs.readthedocs.io/en/release3.7.0beta1/Administrator%20Guide/GlusterFS%20iSCSI/







