module = "File System"
interface_names = [
    "File_System_Xfs_Format",
    "File_System_Xfs_Update",
    "File_System_Mount",
    "File_System_Remount",
    "File_System_Mount_Info",
    "File_System_Bind",
    "File_System_Rebind",
    "File_System_Unmount",
    "File_System_Fstab_List",
    "File_System_Fstab_Update",
    "File_System_Fstab_Delete",
    "File_System_Unmount_recover",
    "Logic_Disk_Wipe_recover"
]


[File_System_Xfs_Format]
interface_desc = "格式化为 XFS Filesystem."
interface_path = "/file_system/xfs_mkfs"
interface_cmd_1 = "/usr/sbin/mkfs.xfs -L DataDisk -i size=2k -n size=64k -d su=128k,sw=4 /dev/sdg"
interface_cmd_2 = "/usr/sbin/xfs_admin -L DataDisk -U 9211c613-98a6-4778-9ffa-05dbef560dd8 /dev/sdg"
requests_data_time = 1
requests_data_1 = { dev_path="/dev/sdg", fs_label="DataDisk", fs_uuid="9211c613-98a6-4778-9ffa-05dbef560dd8", force=false, i_size="2k", n_size="64k", d_su="128k", d_sw="4" }


[File_System_Xfs_Update]
interface_desc = "更新 XFS Label/UUID."
interface_path = "/file_system/xfs_update"
interface_cmd = "/usr/sbin/xfs_admin -L DataDisk -U 2741e75f-fc41-4a64-99ee-82bcc782807f /dev/sdg"
requests_data_time = 1
requests_data_1 = { dev_path="/dev/sdg", fs_label="DataDisk", fs_uuid="2741e75f-fc41-4a64-99ee-82bcc782807f" }


[File_System_Mount]
interface_desc = "挂载文件系统."
interface_path = "/file_system/mount"
interface_cmd = "/usr/bin/mount --types xfs --source /dev/sdg --target /data/2741e75f-fc41-4a64-99ee-82bcc782807f --options _netdev,rw,noatime,inode64,nouuid,nobarrier,logbufs=8,logbsize=256k"
requests_data_time = 1
requests_data_1 = { source="/dev/sdg", target="/data/2741e75f-fc41-4a64-99ee-82bcc782807f", fstype="xfs", options=["_netdev", "rw", "noatime", "inode64", "nouuid", "nobarrier", "logbufs=8", "logbsize=256k"] }


[File_System_Remount]
interface_desc = "重新挂载文件系统."
interface_path = "/file_system/remount"
interface_cmd = "/usr/bin/mount --source /dev/sdg --target /data/2741e75f-fc41-4a64-99ee-82bcc782807f --options remount,_netdev,rw,noatime,inode64,nouuid,nobarrier,logbufs=8,logbsize=256k"
requests_data_time = 1
requests_data_1 = { source="/dev/sdg", target="/data/2741e75f-fc41-4a64-99ee-82bcc782807f", options=["_netdev", "rw", "noatime", "inode64", "nouuid", "nobarrier", "logbufs=8", "logbsize=256k"] }


[File_System_Mount_Info]
interface_desc = "挂载信息."
interface_path = "/file_system/info"
interface_cmd = "/usr/bin/findmnt --all --pairs --output ID,TARGET,UUID,SOURCE"
requests_data_time = 1
requests_data_1 = { sources=["/dev/sdg"], targets=["/data/2741e75f-fc41-4a64-99ee-82bcc782807f"], infos=["UUID"] }


[File_System_Bind]
interface_desc = "绑定文件系统."
interface_path = "/file_system/bind"
interface_cmd = "/usr/bin/mount --bind --options _netdev,rw,noatime /data/2741e75f-fc41-4a64-99ee-82bcc782807f /tmp/2741e75f-fc41-4a64-99ee-82bcc782807f"
requests_data_time = 1
requests_data_1 = { source="/data/2741e75f-fc41-4a64-99ee-82bcc782807f", target="/tmp/2741e75f-fc41-4a64-99ee-82bcc782807f", options=["_netdev", "rw", "noatime"] }


[File_System_Rebind]
interface_desc = "重新绑定文件系统."
interface_path = "/file_system/rebind"
interface_cmd = "/usr/bin/mount --bind --options remount /data/2741e75f-fc41-4a64-99ee-82bcc782807f /tmp/2741e75f-fc41-4a64-99ee-82bcc782807f"
requests_data_time = 1
requests_data_1 = { source="/data/2741e75f-fc41-4a64-99ee-82bcc782807f", target="/tmp/2741e75f-fc41-4a64-99ee-82bcc782807f", options=[] }


[File_System_Unmount]
interface_desc = "卸载文件系统."
interface_path = "/file_system/umount"
interface_cmd = "/usr/bin/umount --lazy /tmp/2741e75f-fc41-4a64-99ee-82bcc782807f"
requests_data_time = 1
requests_data_1 = { target="/tmp/2741e75f-fc41-4a64-99ee-82bcc782807f", lazy=true }


[File_System_Fstab_List]
interface_desc = "获取Fstab信息列表."
interface_path = "/file_system/fstab/list"
requests_data_time = 1
requests_data_1 = {}


[File_System_Fstab_Update]
interface_desc = "增加或更新Fstab Mntent."
interface_path = "/file_system/fstab/update"
requests_data_time = 1
requests_data_1 = { mnt_fsname="/dev/sdg", mnt_dir="/data/2741e75f-fc41-4a64-99ee-82bcc782807f", mnt_type="auto", mnt_opts=["_netdev", "rw", "noatime", "inode64", "nouuid", "nobarrier", "logbufs=8", "logbsize=256k"], mnt_freq=0, mnt_passno=0 }


[File_System_Fstab_Delete]
interface_desc = "删除Fstab Mntent."
interface_path = "/file_system/fstab/delete"
requests_data_time = 1
requests_data_1 = { mnt_fsname="/dev/sdg", mnt_dir="/data/2741e75f-fc41-4a64-99ee-82bcc782807f" }


[File_System_Unmount_recover]
interface_desc = "卸载文件系统."
interface_path = "/file_system/umount"
interface_cmd = "/usr/bin/umount --lazy /data/2741e75f-fc41-4a64-99ee-82bcc782807f"
requests_data_time = 1
requests_data_1 = { target="/data/2741e75f-fc41-4a64-99ee-82bcc782807f", lazy=true }


[Logic_Disk_Wipe_recover]
interface_desc = "块设备擦除，擦除分区信息、软raid、LVM等，不可逆慎重使用."
interface_path = "/storage/logic_disk/wipe"
interface_cmd = "wipefs --all /dev/sdg"
requests_data_time = 1
requests_data_1 = { dev_path="/dev/sdg" }