config:
    name: Nfs Config Import
    base_url: ${ENV(API_URL)}
    variables:
        ret_code: 200
        req_host: 127.0.0.1
        config: --Empty--

teststeps:
-
    name: API
    request:
        url: /cluster/nfs/config/import
        method: POST
        json: ${gen_data(
                req_host=$req_host,
                config=$config
            )}
    validate:
        - eq: ["status_code", $ret_code]
