module = "NFS"
interface_names = [
    "Nfs_Share_Delete",
    "Nfs_Service_Disable"
]


[Nfs_Share_Delete]
interface_desc = "删除NFS共享客户端访问权限"
interface_path = "/cluster/nfs/share/delete"
requests_data_time = 1
[Nfs_Share_Delete.requests_data_1]
req_host="127.0.0.1"
nfs_mode="Kernel"
vol_name="vol-01"
share_dir="/subdir-01"
client="172.18.123.0/24"


[Nfs_Service_Disable]
interface_desc = "关闭NFS服务"
interface_path = "/cluster/nfs/service/disable"
requests_data_time = 1
requests_data_1 = { req_host="127.0.0.1", nfs_mode="Kernel" }