module = "NFS"
interface_names = [
    "Nfs_Service_status",
    "Nfs_Service_Init",
    "Nfs_Service_Enable",
    "Nfs_Share_List",
    "Nfs_Share_Update",
    "Nfs_Client_Status",
]


[Nfs_Service_status]
interface_desc = "获取NFS服务状态"
interface_path = "/cluster/nfs/service/status"
requests_data_time = 1
requests_data_1 = { req_host="127.0.0.1", nfs_mode="Kernel" }


[Nfs_Service_Init]
interface_desc = "初始化NFS配置"
interface_path = "/cluster/nfs/service/init"
requests_data_time = 1
requests_data_1 = { req_host="127.0.0.1", nfs_mode="Kernel" }


[Nfs_Service_Enable]
interface_desc = "开启NFS服务"
interface_path = "/cluster/nfs/service/enable"
requests_data_time = 1
requests_data_1 = { req_host="127.0.0.1", nfs_mode="Kernel" }


[Nfs_Share_List]
interface_desc = "获取NFS共享信息列表"
interface_path = "/cluster/nfs/share/list"
requests_data_time = 1
requests_data_1 = { req_host="127.0.0.1", nfs_mode="Kernel" }


[Nfs_Share_Update]
interface_desc = "增加/更新NFS共享客户端访问权限"
interface_path = "/cluster/nfs/share/update"
requests_data_time = 1
[Nfs_Share_Update.requests_data_1]
req_host="127.0.0.1"
nfs_mode="Kernel"
vol_name="vol-01"
share_dir="/subdir-01"
client="172.18.123.0/24"
readonly=false


[Nfs_Client_Status]
interface_desc = "获取NFS共享的客户端连接状态列表"
interface_path = "/cluster/nfs/client/status"
requests_data_time = 1
requests_data_1 = { req_host="127.0.0.1" }

