# NOTE: Generated By HttpRunner v3.1.6
# FROM: umi_cluster/user_init_node3.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseUserInitNode3(HttpRunner):

    config = Config("create user and group").base_url("${ENV(umi_cluster_url)}")

    teststeps = [
        Step(
            RunRequest("Local Group Update")
            .post("/cluster/user/local/group/update")
            .with_json({"req_host": "127.0.0.1", "group": "group-01", "gid": 1011})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Local Group Update")
            .post("/cluster/user/local/group/update")
            .with_json({"req_host": "127.0.0.1", "group": "group-02", "gid": 1012})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Local Group Update")
            .post("/cluster/user/local/group/update")
            .with_json({"req_host": "127.0.0.1", "group": "group-03", "gid": 1013})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Local Group List")
            .post("/cluster/user/local/group/list")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Local User Update")
            .post("/cluster/user/local/user/update")
            .with_json(
                {
                    "req_host": "127.0.0.1",
                    "user": "user-01",
                    "passwd": "123456",
                    "groups": ["group-01", "group-02", "group-03"],
                    "uid": 1011,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Local User List")
            .post("/cluster/user/local/user/list")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseUserInitNode3().test_start()
