module = "Minio Gateway"
interface_names = [
    "Minio_Gateway_User_Delete",
    "Minio_Gateway_Group_Delete",
    "Minio_Gateway_Policy_Delete",
    "Minio_Gateway_Bucket_Delete",
    "Minio_Gateway_Service_Disable",
    "Minio_Gateway_Config_Delete"
]


[Minio_Gateway_User_Delete]
interface_desc = "删除对象网关用户"
interface_path = "/cluster/minio/gateway/user/delete"
requests_data_time = 1
[Minio_Gateway_User_Delete.requests_data_1]
req_host="127.0.0.1"
config="config01"
username=["user01"]


[Minio_Gateway_Group_Delete]
interface_desc = "删除对象网关组"
interface_path = "/cluster/minio/gateway/group/delete"
requests_data_time = 1
[Minio_Gateway_Group_Delete.requests_data_1]
req_host="127.0.0.1"
config="config01"
group=["group01"]


[Minio_Gateway_Policy_Delete]
interface_desc = "删除对象网关策略"
interface_path = "/cluster/minio/gateway/policy/delete"
requests_data_time = 1
[Minio_Gateway_Policy_Delete.requests_data_1]
req_host="127.0.0.1"
config="config01"
policy=["policy01"]


[Minio_Gateway_Bucket_Delete]
interface_desc = "删除桶配置"
interface_path = "/cluster/minio/gateway/bucket/delete"
requests_data_time = 1
[Minio_Gateway_Bucket_Delete.requests_data_1]
req_host="127.0.0.1"
config="config01"
bucket="bucket01"
force=false


[Minio_Gateway_Service_Disable]
interface_desc = "停用对象网关服务并从开机自启列表中移除"
interface_path = "/cluster/minio/gateway/service/disable"
requests_data_time = 1
[Minio_Gateway_Service_Disable.requests_data_1]
req_host="127.0.0.1"
config_list=["config01"]


[Minio_Gateway_Config_Delete]
interface_desc = "删除对象网关配置"
interface_path = "/cluster/minio/gateway/config/delete"
requests_data_time = 1
[Minio_Gateway_Config_Delete.requests_data_1]
req_host="127.0.0.1"
config="config01"
force=false


