module = "Minio Gateway"
interface_names = [
    "Minio_Gateway_Service_Status",
    "Minio_Gateway_Service_Init",
    "Minio_Gateway_Config_Update",
    "Minio_Gateway_Config_List",
    "Minio_Gateway_Service_Enable",
    "Minio_Gateway_Bucket_Update",
    "Minio_Gateway_Bucket_List",
    "Minio_Gateway_Policy_List",
    "Minio_Gateway_Policy_Update",
    "Minio_Gateway_Policy_Info",
    "Minio_Gateway_Gruop_List",
    "Minio_Gateway_Gruop_Update",
    "Minio_Gateway_Gruop_Info",
    "Minio_Gateway_User_List",
    "Minio_Gateway_User_Update",
    "Minio_Gateway_User_Info"
]


[Minio_Gateway_Service_Status]
interface_desc = "查询对象网关服务状态"
interface_path = "/cluster/minio/gateway/service/status"
requests_data_time = 1
[Minio_Gateway_Service_Status.requests_data_1]
req_host="127.0.0.1"


[Minio_Gateway_Service_Init]
interface_desc = "初始化Minio配置,不会删除已经存在的配置"
interface_path = "/cluster/minio/gateway/service/init"
requests_data_time = 1
[Minio_Gateway_Service_Init.requests_data_1]
req_host="127.0.0.1"
config_list=["config01"]


[Minio_Gateway_Config_List]
interface_desc = "获取对象网关配置列表"
interface_path = "/cluster/minio/gateway/config/list"
requests_data_time = 1
[Minio_Gateway_Config_List.requests_data_1]
req_host="127.0.0.1"
config_list=["config01"]


[Minio_Gateway_Config_Update]
interface_desc = "获取对象网关配置列表"
interface_path = "/cluster/minio/gateway/config/update"
requests_data_time = 1
[Minio_Gateway_Config_Update.requests_data_1]
req_host="127.0.0.1"
config="config01"
minio_admin_user="minio"
minio_admin_password="12345678"
api_port=9000
console_port=19000
workdir="/mnt/xdfs-gateway-config01"


[Minio_Gateway_Service_Enable]
interface_desc = "启用对象网关服务并添加到开机自启列表中"
interface_path = "/cluster/minio/gateway/service/enable"
requests_data_time = 1
[Minio_Gateway_Service_Enable.requests_data_1]
req_host="127.0.0.1"
config_list=["config01"]


[Minio_Gateway_Bucket_List]
interface_desc = "启用对象网关服务并添加到开机自启列表中"
interface_path = "/cluster/minio/gateway/bucket/list"
requests_data_time = 1
[Minio_Gateway_Bucket_List.requests_data_1]
req_host="127.0.0.1"
config="config01"


[Minio_Gateway_Bucket_Update]
interface_desc = "启用对象网关服务并添加到开机自启列表中"
interface_path = "/cluster/minio/gateway/bucket/update"
requests_data_time = 1
[Minio_Gateway_Bucket_Update.requests_data_1]
req_host="127.0.0.1"
config="config01"
bucket="bucket01"
policy="none"


[Minio_Gateway_Policy_List]
interface_desc = "获取对象网关策略列表"
interface_path = "/cluster/minio/gateway/policy/list"
requests_data_time = 1
[Minio_Gateway_Policy_List.requests_data_1]
req_host="127.0.0.1"
config="config01"


[Minio_Gateway_Policy_Info]
interface_desc = "获取对象网关策略详细配置信息"
interface_path = "/cluster/minio/gateway/policy/info"
requests_data_time = 1
[Minio_Gateway_Policy_Info.requests_data_1]
req_host="127.0.0.1"
config="config01"
policy=["policy01"]


[Minio_Gateway_Policy_Update]
interface_desc = "添加/更新对象网关策略"
interface_path = "/cluster/minio/gateway/policy/update"
requests_data_time = 1
[Minio_Gateway_Policy_Update.requests_data_1]
req_host="127.0.0.1"
config="config01"
policy="policy01"
[Minio_Gateway_Policy_Update.requests_data_1.raw]
Version="2012-10-17"
Statement=[{Effect="Allow", Action=["s3:*"],Resource=["arn:aws:s3:::bucket01/*"]}]


[Minio_Gateway_Gruop_List]
interface_desc = "获取对象网关组列表"
interface_path = "/cluster/minio/gateway/group/list"
requests_data_time = 1
[Minio_Gateway_Gruop_List.requests_data_1]
req_host="127.0.0.1"
config="config01"


[Minio_Gateway_Gruop_Info]
interface_desc = "获取对象网关组详细配置信息"
interface_path = "/cluster/minio/gateway/group/info"
requests_data_time = 1
[Minio_Gateway_Gruop_Info.requests_data_1]
req_host="127.0.0.1"
config="config01"
group=["group01"]


[Minio_Gateway_Gruop_Update]
interface_desc = "添加/更新对象网关组"
interface_path = "/cluster/minio/gateway/group/update"
requests_data_time = 1
[Minio_Gateway_Gruop_Update.requests_data_1]
req_host="127.0.0.1"
config="config01"
group="group01"
username=["user01"]
policy=["policy01"]
enable=true


[Minio_Gateway_User_List]
interface_desc = "获取对象网关用户列表"
interface_path = "/cluster/minio/gateway/user/list"
requests_data_time = 1
[Minio_Gateway_User_List.requests_data_1]
req_host="127.0.0.1"
config="config01"


[Minio_Gateway_User_Info]
interface_desc = "获取对象网关用户详细配置信息"
interface_path = "/cluster/minio/gateway/user/info"
requests_data_time = 1
[Minio_Gateway_User_Info.requests_data_1]
req_host="127.0.0.1"
config="config01"
username=["user01"]


[Minio_Gateway_User_Update]
interface_desc = "添加/更新对象网关用户"
interface_path = "/cluster/minio/gateway/user/update"
requests_data_time = 1
[Minio_Gateway_User_Update.requests_data_1]
req_host="127.0.0.1"
config="config01"
username="user01"
password="12345678"
group=["group01"]
policy=["policy01"]
enable=true

















