module = "User"
interface_names = [
    "Local_Group_List",
    "Local_User_List",
    "Local_Group_Update",
    "Local_User_Update"
]


[Local_Group_List]
interface_desc = "获取本地组信息列表，gid(1000-60000)"
interface_path = "/cluster/user/local/group/list"
requests_data_time = 3
requests_data_1 = { req_host="172.18.123.71" }
requests_data_2 = { req_host="172.18.123.72" }
requests_data_3 = { req_host="172.18.123.73" }


[Local_Group_Update]
interface_desc = "添加本地组/修改组gid"
interface_path = "/cluster/user/local/group/update"
requests_data_time = 12
requests_data_1 = { req_host="172.18.123.71", group="group-01", gid=1001 }
requests_data_2 = { req_host="172.18.123.71", group="group-02", gid=1002 }
requests_data_3 = { req_host="172.18.123.71", group="group-03", gid=1003 }
requests_data_4 = { req_host="172.18.123.71", group="group-04", gid=1004 }
requests_data_5 = { req_host="172.18.123.72", group="group-01", gid=1001 }
requests_data_6 = { req_host="172.18.123.72", group="group-02", gid=1002 }
requests_data_7 = { req_host="172.18.123.72", group="group-03", gid=1003 }
requests_data_8 = { req_host="172.18.123.72", group="group-04", gid=1004 }
requests_data_9 = { req_host="172.18.123.73", group="group-01", gid=1001 }
requests_data_10 = { req_host="172.18.123.73", group="group-02", gid=1002 }
requests_data_11 = { req_host="172.18.123.73", group="group-03", gid=1003 }
requests_data_12 = { req_host="172.18.123.73", group="group-04", gid=1004 }


[Local_User_List]
interface_desc = "获取所有节点本地用户信息列表，uid(1000-60000)"
interface_path = "/cluster/user/local/user/list"
requests_data_time = 3
requests_data_1 = { req_host="172.18.123.71" }
requests_data_2 = { req_host="172.18.123.72" }
requests_data_3 = { req_host="172.18.123.73" }


[Local_User_Update]
interface_desc = "添加本地用户/修改用户信息"
interface_path = "/cluster/user/local/user/update"
requests_data_time = 6
[Local_User_Update.requests_data_1]
req_host="172.18.123.71"
user="user-01"
passwd="123456"
groups=["group-01", "group-02", "group-03", "group-04"]
uid=1001
[Local_User_Update.requests_data_2]
req_host="172.18.123.71"
user="user-02"
passwd="123456"
groups=["group-01", "group-02", "group-03", "group-04"]
uid=1002
[Local_User_Update.requests_data_3]
req_host="172.18.123.72"
user="user-01"
passwd="123456"
groups=["group-01", "group-02", "group-03", "group-04"]
uid=1001
[Local_User_Update.requests_data_4]
req_host="172.18.123.72"
user="user-02"
passwd="123456"
groups=["group-01", "group-02", "group-03", "group-04"]
uid=1002
[Local_User_Update.requests_data_5]
req_host="172.18.123.73"
user="user-01"
passwd="123456"
groups=["group-01", "group-02", "group-03", "group-04"]
uid=1001
[Local_User_Update.requests_data_6]
req_host="172.18.123.73"
user="user-02"
passwd="123456"
groups=["group-01", "group-02", "group-03", "group-04"]
uid=1002




