module = "User"
interface_names = [
    "Local_User_Delete",
    "Local_Group_Delete"
]


[Local_Group_Delete]
interface_desc = "删除本地组"
interface_path = "/cluster/user/local/group/delete"
requests_data_time = 12
requests_data_1 = { req_host="172.18.123.71", group="group-01" }
requests_data_2 = { req_host="172.18.123.71", group="group-02" }
requests_data_3 = { req_host="172.18.123.71", group="group-03" }
requests_data_4 = { req_host="172.18.123.71", group="group-04" }
requests_data_5 = { req_host="172.18.123.72", group="group-01" }
requests_data_6 = { req_host="172.18.123.72", group="group-02" }
requests_data_7 = { req_host="172.18.123.72", group="group-03" }
requests_data_8 = { req_host="172.18.123.72", group="group-04" }
requests_data_9 = { req_host="172.18.123.73", group="group-01" }
requests_data_10 = { req_host="172.18.123.73", group="group-02" }
requests_data_11 = { req_host="172.18.123.73", group="group-03" }
requests_data_12 = { req_host="172.18.123.73", group="group-04" }


[Local_User_Delete]
interface_desc = "删除本地用户"
interface_path = "/cluster/user/local/user/delete"
requests_data_time = 6
requests_data_1 = { req_host="172.18.123.71", user="user-01" }
requests_data_2 = { req_host="172.18.123.71", user="user-02" }
requests_data_3 = { req_host="172.18.123.72", user="user-01" }
requests_data_4 = { req_host="172.18.123.72", user="user-02" }
requests_data_5 = { req_host="172.18.123.73", user="user-01" }
requests_data_6 = { req_host="172.18.123.73", user="user-02" }

