# NOTE: Generated By HttpRunner v3.1.6
# FROM: umi_cluster/info_node3.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseInfoNode3(HttpRunner):

    config = Config("${ENV(umi_cluster_test_title)}").base_url(
        "${ENV(umi_cluster_url)}"
    )

    teststeps = [
        Step(
            RunRequest("Network Interface Status")
            .post("/network/interface/status")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Block Device Status")
            .post("/storage/block_device/status")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("File System Status")
            .post("/storage/file_system/status")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Cluster Node List")
            .post("/cluster/node/list")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Cluster Volume Info")
            .post("/cluster/volume/info")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Local User List")
            .post("/cluster/user/local/user/list")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Local Group List")
            .post("/cluster/user/local/group/list")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Posix Share List")
            .post("/cluster/posix/share/list")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseInfoNode3().test_start()
