# NOTE: Generated By HttpRunner v3.1.6
# FROM: umi_cluster/user_uninit_node3.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseUserUninitNode3(HttpRunner):

    config = Config("${ENV(umi_cluster_test_title)}").base_url(
        "${ENV(umi_cluster_url)}"
    )

    teststeps = [
        Step(
            RunRequest("Local User Delete")
            .post("/cluster/user/local/user/delete")
            .with_json({"req_host": "127.0.0.1", "user": "user-01"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Local Group Delete")
            .post("/cluster/user/local/group/delete")
            .with_json({"req_host": "127.0.0.1", "group": "group-01"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Local Group Delete")
            .post("/cluster/user/local/group/delete")
            .with_json({"req_host": "127.0.0.1", "group": "group-02"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Local Group Delete")
            .post("/cluster/user/local/group/delete")
            .with_json({"req_host": "127.0.0.1", "group": "group-03"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseUserUninitNode3().test_start()
