# NOTE: Generated By HttpRunner v3.1.6
# FROM: umi_cluster/volume_build_init_node2.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseVolumeBuildInitNode2(HttpRunner):

    config = Config("${ENV(umi_cluster_test_title)}").base_url(
        "${ENV(umi_cluster_url)}"
    )

    teststeps = [
        Step(
            RunRequest("Block Device Wipe")
            .post("/storage/block_device/wipe")
            .with_json({"req_host": "172.18.123.72", "dev_path": "/dev/sde"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Block Device Init")
            .post("/storage/block_device/init")
            .with_json({"req_host": "172.18.123.72", "dev_path": "/dev/sde"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Block Device Enable")
            .post("/storage/block_device/enable")
            .with_json({"req_host": "172.18.123.72", "dev_path": "/dev/sde"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Block Device Disable")
            .post("/storage/block_device/disable")
            .with_json({"req_host": "172.18.123.72", "dev_path": "/dev/sde"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseVolumeBuildInitNode2().test_start()
