# NOTE: Generated By HttpRunner v3.1.6
# FROM: umi_cluster/volume_iscsi_init_node3.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseVolumeIscsiInitNode3(HttpRunner):

    config = Config("${ENV(umi_cluster_test_title)}").base_url(
        "${ENV(umi_cluster_url)}"
    )

    teststeps = [
        Step(
            RunRequest("Iscsi Service Status")
            .post("/cluster/iscsi/service/status")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Service Init")
            .post("/cluster/iscsi/service/init")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Service Disable")
            .post("/cluster/iscsi/service/disable")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Service Enable")
            .post("/cluster/iscsi/service/enable")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi User Update")
            .post("/cluster/iscsi/user/update")
            .with_json({"req_host": "127.0.0.1", "user": "usr-01", "passwd": "123456"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi User Update")
            .post("/cluster/iscsi/user/update")
            .with_json({"req_host": "127.0.0.1", "user": "usr-01", "passwd": "123456"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi User Update")
            .post("/cluster/iscsi/user/update")
            .with_json({"req_host": "127.0.0.1", "user": "usr-03", "passwd": "123456"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi User List")
            .post("/cluster/iscsi/user/list")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Lun Update")
            .post("/cluster/iscsi/lun/update")
            .with_json(
                {
                    "req_host": "127.0.0.1",
                    "lun_name": "lun-01",
                    "lun_size": "10 MiB",
                    "vol_name": "umi_test",
                    "thin": True,
                    "glfs_api": True,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Lun Update")
            .post("/cluster/iscsi/lun/update")
            .with_json(
                {
                    "req_host": "127.0.0.1",
                    "lun_name": "lun-02",
                    "lun_size": "10 MiB",
                    "vol_name": "umi_test",
                    "thin": True,
                    "glfs_api": True,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Lun List")
            .post("/cluster/iscsi/lun/list")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Lun Status")
            .post("/cluster/iscsi/lun/status")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Target Update")
            .post("/cluster/iscsi/target/update")
            .with_json(
                {
                    "req_host": "127.0.0.1",
                    "iqn": "iqn.2021-08.cluster-01.target-01",
                    "client_addrs": ["127.0.0.1", "172.16.1.0/24"],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Target List")
            .post("/cluster/iscsi/target/list")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Target Status")
            .post("/cluster/iscsi/target/Status")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Target User Map")
            .post("/cluster/iscsi/target/user_map")
            .with_json(
                {
                    "req_host": "127.0.0.1",
                    "iqn": "iqn.2021-08.cluster-01.target-01",
                    "incoming_users": ["usr-01", "usr-02"],
                    "outgoing_user": "usr-03",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Target User Map")
            .post("/cluster/iscsi/target/user_map")
            .with_json(
                {
                    "req_host": "127.0.0.1",
                    "iqn": "iqn.2021-08.cluster-01.target-01",
                    "luns": ["lun-01", "lun-02"],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseVolumeIscsiInitNode3().test_start()
