# NOTE: Generated By HttpRunner v3.1.6
# FROM: umi_cluster/volume_iscsi_uninit_node3.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseVolumeIscsiUninitNode3(HttpRunner):

    config = Config("${ENV(umi_cluster_test_title)}").base_url(
        "${ENV(umi_cluster_url)}"
    )

    teststeps = [
        Step(
            RunRequest("Iscsi User Delete")
            .post("/cluster/iscsi/user/delete")
            .with_json({"req_host": "127.0.0.1", "user": "usr-01"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi User Delete")
            .post("/cluster/iscsi/user/delete")
            .with_json({"req_host": "127.0.0.1", "user": "usr-01"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi User Delete")
            .post("/cluster/iscsi/user/delete")
            .with_json({"req_host": "127.0.0.1", "user": "usr-03"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Lun Delete")
            .post("/cluster/iscsi/lun/delete")
            .with_json(
                {"req_host": "127.0.0.1", "lun_name": "lun-01", "clean_data": True}
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Lun Delete")
            .post("/cluster/iscsi/lun/delete")
            .with_json(
                {"req_host": "127.0.0.1", "lun_name": "lun-02", "clean_data": True}
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Iscsi Target Delete")
            .post("/cluster/iscsi/target/delete")
            .with_json(
                {"req_host": "127.0.0.1", "iqn": "iqn.2021-08.cluster-01.target-01"}
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseVolumeIscsiUninitNode3().test_start()
