# NOTE: Generated By HttpRunner v3.1.6
# FROM: umi_cluster/volume_posix_node3.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseVolumePosixNode3(HttpRunner):

    config = Config("${ENV(umi_cluster_test_title)}").base_url(
        "${ENV(umi_cluster_url)}"
    )

    teststeps = [
        Step(
            RunRequest("Posix Share List")
            .post("/cluster/posix/share/list")
            .with_json({"req_host": "127.0.0.1"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Posix Share Update")
            .post("/cluster/posix/share/update")
            .with_json(
                {
                    "req_host": "127.0.0.1",
                    "vol_name": "umi_test",
                    "share_dir": "/subdir-test",
                    "allow_hosts": ["172.18.123.0/24", "172.169.100.11"],
                    "deny_hosts": ["192.168.2.0/24"],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("Posix Share Delete")
            .post("/cluster/posix/share/delete")
            .with_json(
                {
                    "req_host": "127.0.0.1",
                    "vol_name": "umi_test",
                    "share_dir": "/subdir-test",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseVolumePosixNode3().test_start()
