module = "FTP"
interface_names = [
    "Smbftpd_Service_Enable",
    "Smbftpd_Service_Status",
    "Smbftpd_Cfg_List",
    "Smbftpd_Cfg_Update",
    "Smbftpd_Scfg_List",
    "Smbftpd_Scfg_Update"
]


[Smbftpd_Service_Enable]
interface_desc = "开启FTP服务"
interface_path = "/cluster/smbftpd/service/enable"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


[Smbftpd_Service_Status]
interface_desc = "获取FTP服务状态"
interface_path = "/cluster/smbftpd/service/status"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


[Smbftpd_Cfg_List]
interface_desc = "获取 smbftpd conf 配置文件信息"
interface_path = "/cluster/smbftpd/cfg/list"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


[Smbftpd_Cfg_Update]
interface_desc = "获取 smbftpd conf 配置文件信息"
interface_path = "/cluster/smbftpd/cfg/update"
requests_data_time = 1
[Smbftpd_Cfg_Update.requests_data_1]
req_host = "127.0.0.1"
ServerName = "xdfs"
ShowProgramVersion = true
Port = 21
EmptyPasswdLogin = true
AnonymousLogin = true
DefaultMode = "SMB"
ShareConfPath = "/usr/local/etc/smbftpd/smbftpd_share.conf"
LogCommand = true
DoWtmpLog = true
DebugMode = true
TransferLog = "/var/log/smbftpd.log"
RequireValidShell = false
SecurityPolicyMode = 1
SSLKeyFile = "/usr/local/etc/smbftpd/ssl.key/server.key"
SSLCertFile = "/usr/local/etc/smbftpd/ssl.crt/server.crt"


[Smbftpd_Scfg_List]
interface_desc = "获取 smbftpd conf 配置文件信息"
interface_path = "/cluster/smbftpd/scfg/list"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


[Smbftpd_Scfg_Update]
interface_desc = "获取 smbftpd conf 配置文件信息"
interface_path = "/cluster/smbftpd/scfg/update"
requests_data_time = 1
[Smbftpd_Scfg_Update.requests_data_1]
req_host = "127.0.0.1"
share_name = "share-01"
path = "/data/e280f95a-6a6a-4c88-817d-fea9fefdb8f9/share-01"
rw = "user-01"
ro = "user-01"
browseable = true
disable_ls = "anonymous, @user-01"
disable_modify = "anonymous, @user-01"
disable_download = "anonymous, @user-01"




