module = "FTP"
interface_names = [
    "Smbftpd_Scfg_delete",
    "Smbftpd_Service_Disable"
]


[Smbftpd_Scfg_delete]
interface_desc = "删除指定 smbftpd share"
interface_path = "/cluster/smbftpd/scfg/delete"
requests_data_time = 1
[Smbftpd_Scfg_delete.requests_data_1]
req_host = "172.18.123.73"
share_name = "share-01"


[Smbftpd_Service_Disable]
interface_desc = "获取CIFS服务状态"
interface_path = "/cluster/smbftpd/service/disable"
requests_data_time = 1
requests_data_1 = { req_host="172.18.123.73" }


